Mute flaky CompositeIndexWriterForAppendTests
Muting the entire class because some of the failures are file leaks
detected during teardown, so I'm not sure which test method is causing
the problem.

```
CompositeIndexWriterForAppendTests > classMethod FAILED
    java.lang.RuntimeException: file handle leaks:
[FileChannel(/var/jenkins/workspace/gradle-check/search/server/build/testrun/test/temp/org.opensearch.index.engine.CompositeIndexWriterForAppendTests_5D4C13243992BC3C-001/index-MMapDirectory-001/write.lock)]
```

Signed-off-by: Andrew Ross <andrross@amazon.com>