Add missing @param javadoc on AllocationRejection.wrap(Runnable) overload
The Runnable overload of AllocationRejection.wrap was missing @param tags
for context and body, failing the missingJavadoc gradle-check on CI:

  AllocationRejection.java:75: error: AllocationRejection.wrap (method):
    missing javadoc @param for parameter 'context'

Mirror the @param/@throws structure already present on the Supplier
overload above.

Signed-off-by: Gaurav Singh <snghsvn@amazon.com>