Fix repository-gcs KeyStore.getInstance type/provider order (#22288) (#22834)
GoogleCloudStorageService.createFipsCompliantGoogleTrustStore called
KeyStore.getInstance("BCFIPS", "BCFIPS"), but "BCFIPS" is the
provider name; the corresponding keystore type is "BCFKS" (already
documented in the in-method comment one line above). Every GCS snapshot
operation on a FIPS-enabled OpenSearch 3.7.0 distribution therefore
fails with:

  KeyStoreException: BCFIPS not found
    caused by: NoSuchAlgorithmException: no such algorithm: BCFIPS for
    provider BCFIPS

Fixes #22287.


(cherry picked from commit 24a14b9cb0889d300df4989150da6064e11d7461)

Signed-off-by: Guillaume SZKOPINSKI <guillaume.szkopinski@altirnao.com>
Signed-off-by: opensearch-ci-bot <opensearch-infra@amazon.com>
Co-authored-by: Guillaume SZKOPINSKI <guillaume.szkopinski@altirnao.com>